time_intervals:
  # fight time interval default: 25 minutes
  send_heros_for_fight: 25
  # game action time interval default 8 minutes
  boss_hunt_action: 8
  interval_between_movements: 1
  report_no_action: 30

threshold:
  default: 0.7
  common: 0.8
  select_wallet_buttons: 0.8
  go_to_work_btn: 0.9
  green_bar: 0.9
  stamina: 1.0

scroll_size: 100
scroll_attemps: 5
scroll_map_attemps: 8
use_click_and_drag_instead_of_scroll: true
click_and_drag_amount: 200
select_heroes_mode: "stamina"
save_log_to_file: True

window_width: 1100
window_height: 800

window_min_width: 1100
window_min_height: 800

# To enable refresh browser. value is hours.
# 0 = disable
refresh_browser: 0

# Stop boss hunt when completed on maps. default 0
# 0 is no stop
stop_when_completed_map: 0
# Set heros per fight default 3
hero_per_fight: 3

enable_hero_low_rarity_map_10_only: True
# enable move mouse between waiting fight
waiting_fight_move_mouse: False
# enable line notification
enable_line_notify: False
line_api_url: "https://notify-api.line.me/api/notify"
line_token: ""
