time_intervals:
  # fight time interval default: 25 minutes
  send_heros_for_fight: 25
  # game action time interval default 8 minutes
  boss_hunt_action: 8
  interval_between_movements: 1
  report_no_action: 30
  check_for_login: 60
  check_server_online: 60

threshold:
  default: 0.7
  common: 0.8
  select_wallet_buttons: 0.8
  go_to_work_btn: 0.9
  green_bar: 0.9
  stamina: 1.0
  energy_0: 0.94
  energy_1: 0.94
  energy_2: 0.96
  energy_3: 0.91
  energy_x: 0.99

scroll_size: 100
scroll_attemps: 5
scroll_map_attemps: 8
use_click_and_drag_instead_of_scroll: true
click_and_drag_amount: 200
select_heroes_mode: "stamina"
save_log_to_file: True

window_width: 1000
window_height: 690

window_min_width: 1000
window_min_height: 690

# To enable refresh browser. value is hours.
# 0 = disable
refresh_browser: 0

# Stop boss hunt when completed on maps. default 0
# 0 is no stop
stop_when_completed_map: 0
# Set heros per fight default 3
hero_per_fight: 3
minimum_hero_per_fight: 3

enable_lowest_rarity_fight_on_map10_only: False
# enable move mouse between waiting fight
waiting_fight_move_mouse: False
# enable line notification
enable_line_notify: False
enable_notify_with_picture: False
line_api_url: "https://notify-api.line.me/api/notify"
line_token: ""

enable_write_report: False

enable_break_time: False
breaks:
  -
    start: '06:58:00'
    end: '08:00:00'
enable_team_arrangement: False
tesseract_cmd: ""
teams:
  -
    a:
      heros:
        - 999999
        - 999999
        - 999999
      fight_map_10: True